### ISSUE TITLE
rtcrthread: Unexpected exception of type <'exceptions.TypeError'>

### ISSUE THREAD

**Issue by Nebules** [gjr80/weewx-realtime_clientraw#1] opened 2019-07-26 22:38 UTC
My dad has Weewx 3.8.2 reading data from an Acurite 01536 station, and I installed your extension to generate clientraw.txt files.  But I'm running into an error as described in the syslog lines below.  Any idea on how I can resolve this? Thanks -Ben

Jul 26 17:24:26 raspberrypi weewx[1395]: engine: RealtimeClientraw will generate clientraw.txt. min_interval is None
Jul 26 17:24:26 raspberrypi weewx[1395]: engine: Starting up weewx version 3.8.2
Jul 26 17:24:26 raspberrypi weewx[1395]: engine: Starting main packet loop.
Jul 26 17:24:26 raspberrypi weewx[1395]: rtcrthread: Unexpected exception of type <type 'exceptions.TypeError'>
Jul 26 17:24:26 raspberrypi weewx[1395]: rtcrthread: Thread exiting. Reason: unsupported operand type(s) for -: 'float' and 'NoneType'

**Comment by gjr80** [comment] 2019-07-27 12:13
Hi Ben,

I’m currently away from home and relying on my iPad only so this may be a bit painstaking. Could I get you to edit weewx.conf and set debug = 1. Save weewx.conf then restart WeeWX. This will not prevent the error but it should give me a bit more info in the log. Assuming the error appears again could you post a log extract showing the error, be generous and post as much as you can (say up to 10 minutes) before the error. I suspect the issue is to do with your station emitting partial loop packets and my code not being robust enough to handle this. Anyway, let’s see how debug = 1 goes.

**Comment by JonFear** [comment] 2019-08-16 20:35
Hi Gary

I am also seeing this...Davis VP2 IP. Trying to move from WDisplay to a more linux solution!

Jon

Aug 16 21:26:23 weewx weewx[1454]: Starting weewx weather system: weewx.
Aug 16 21:26:23 weewx systemd[1]: Started LSB: weewx weather system.
Aug 16 21:26:23 weewx weewx[1468]: engine: Using configuration file /etc/weewx/weewx.conf
Aug 16 21:26:23 weewx weewx[1468]: engine: Debug is 1
Aug 16 21:26:23 weewx weewx[1468]: engine: Initializing engine
Aug 16 21:26:23 weewx weewx[1468]: engine: Loading station type Vantage (weewx.drivers.vantage)
Aug 16 21:26:23 weewx weewx[1468]: vantage: Driver version is 3.1.1
Aug 16 21:26:23 weewx weewx[1468]: vantage: Opened up ethernet host 192.168.10.31 on port 22222. timeout=4.0, tcp_send_delay=0.5
Aug 16 21:26:23 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:26:24 weewx weewx[1468]: vantage: Hardware type is 16
Aug 16 21:26:28 weewx weewx[1468]: vantage: ISS ID is 1
Aug 16 21:26:28 weewx weewx[1468]: vantage: Hardware name: Vantage Pro2
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdTimeSynch
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdTimeSynch
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdConvert
Aug 16 21:26:28 weewx weewx[1468]: engine: StdConvert target unit is 0x1
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdConvert
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdCalibrate
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdCalibrate
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdQC
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdQC
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.wxservices.StdWXCalculate
Aug 16 21:26:28 weewx weewx[1468]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=prefer_hardware, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Aug 16 21:26:28 weewx weewx[1468]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.wxservices.StdWXCalculate
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdArchive
Aug 16 21:26:28 weewx weewx[1468]: engine: Archive will use data binding wx_binding
Aug 16 21:26:28 weewx weewx[1468]: engine: Record generation will be attempted in 'hardware'
Aug 16 21:26:28 weewx weewx[1468]: engine: Using archive interval of 60 seconds (specified by hardware)
Aug 16 21:26:28 weewx weewx[1468]: engine: Use LOOP data in hi/low calculations: 1
Aug 16 21:26:28 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:26:28 weewx weewx[1468]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Aug 16 21:26:28 weewx weewx[1468]: manager: Starting backfill of daily summaries
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdArchive
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.restx.StdStationRegistry
Aug 16 21:26:28 weewx weewx[1468]: restx: StationRegistry: Registration not requested.
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.restx.StdStationRegistry
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.restx.StdWunderground
Aug 16 21:26:28 weewx weewx[1468]: restx: Wunderground: Posting not enabled.
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.restx.StdWunderground
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.restx.StdPWSweather
Aug 16 21:26:28 weewx weewx[1468]: restx: PWSweather: Posting not enabled.
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.restx.StdPWSweather
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.restx.StdCWOP
Aug 16 21:26:28 weewx weewx[1468]: restx: CWOP: Posting not enabled.
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.restx.StdCWOP
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.restx.StdWOW
Aug 16 21:26:28 weewx weewx[1468]: restx: WOW: Posting not enabled.
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.restx.StdWOW
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.restx.StdAWEKAS
Aug 16 21:26:28 weewx weewx[1468]: restx: AWEKAS: Posting not enabled.
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.restx.StdAWEKAS
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdPrint
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdPrint
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service weewx.engine.StdReport
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service weewx.engine.StdReport
Aug 16 21:26:28 weewx weewx[1468]: engine: Loading service user.rtcr.RealtimeClientraw
Aug 16 21:26:28 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:26:28 weewx weewx[1468]: engine: RealtimeClientraw will generate clientraw.txt. min_interval is None
Aug 16 21:26:28 weewx weewx[1468]: engine: Finished loading service user.rtcr.RealtimeClientraw
Aug 16 21:26:28 weewx weewx[1468]: engine: Starting up weewx version 3.9.2
Aug 16 21:26:28 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:26:28 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:26:29 weewx weewx[1468]: engine: Clock error is -0.63 seconds (positive is fast)
Aug 16 21:26:29 weewx weewx[1468]: vantage: Getting archive packets since 2019-08-16 21:25:00 BST (1565987100)
Aug 16 21:26:30 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:26:31 weewx weewx[1468]: vantage: Retrieving 1 page(s); starting index= 3
Aug 16 21:26:32 weewx weewx[1468]: manager: Added record 2019-08-16 21:26:00 BST (1565987160) to database 'weewx.sdb'
Aug 16 21:26:32 weewx weewx[1468]: manager: Added record 2019-08-16 21:26:00 BST (1565987160) to daily summary in 'weewx.sdb'
Aug 16 21:26:32 weewx weewx[1468]: vantage: DMPAFT complete: page timestamp 2019-08-15 02:39:00 BST (1565833140) less than final timestamp 2019-08-16 21:26:00 BST (1565987160)
Aug 16 21:26:32 weewx weewx[1468]: vantage: Catch up complete.
Aug 16 21:26:32 weewx weewx[1468]: engine: Starting main packet loop.
Aug 16 21:26:32 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:26:33 weewx weewx[1468]: vantage: Requesting 200 LOOP packets.
Aug 16 21:26:33 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:26:34 weewx weewx[1468]: rtcrthread: Unexpected exception of type <type 'exceptions.TypeError'>
Aug 16 21:26:34 weewx weewx[1468]: *** Traceback (most recent call last):
Aug 16 21:26:34 weewx weewx[1468]: ***   File "/usr/share/weewx/user/rtcr.py", line 761, in run
Aug 16 21:26:34 weewx weewx[1468]: ***     self.process_packet(_package['payload'])
Aug 16 21:26:34 weewx weewx[1468]: ***   File "/usr/share/weewx/user/rtcr.py", line 800, in process_packet
Aug 16 21:26:34 weewx weewx[1468]: ***     self.buffer.add_packet(packet_wx)
Aug 16 21:26:34 weewx weewx[1468]: ***   File "/usr/share/weewx/user/rtcr.py", line 2200, in add_packet
Aug 16 21:26:34 weewx weewx[1468]: ***     obs in HIST_MANIFEST, obs in SUM_MANIFEST)
Aug 16 21:26:34 weewx weewx[1468]: ***   File "/usr/share/weewx/user/rtcr.py", line 2229, in add_wind_value
Aug 16 21:26:34 weewx weewx[1468]: ***     packet['dateTime'], False, True, False)
Aug 16 21:26:34 weewx weewx[1468]: ***   File "/usr/share/weewx/user/rtcr.py", line 1866, in _add_value
Aug 16 21:26:34 weewx weewx[1468]: ***     math.cos(math.radians(90.0 - w_dir)),
Aug 16 21:26:34 weewx weewx[1468]: *** TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Aug 16 21:26:34 weewx weewx[1468]: rtcrthread: Thread exiting. Reason: unsupported operand type(s) for -: 'float' and 'NoneType'
Aug 16 21:27:15 weewx weewx[1468]: vantage: Getting archive packets since 2019-08-16 21:26:00 BST (1565987160)
Aug 16 21:27:20 weewx weewx[1468]: vantage: Retry  #0 failed
Aug 16 21:27:24 weewx weewx[1468]: vantage: ip-read error: timed out
Aug 16 21:27:24 weewx weewx[1468]: vantage: Retry  #1 failed
Aug 16 21:27:25 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:27:26 weewx weewx[1468]: vantage: Retrieving 1 page(s); starting index= 4
Aug 16 21:27:26 weewx weewx[1468]: manager: Added record 2019-08-16 21:27:00 BST (1565987220) to database 'weewx.sdb'
Aug 16 21:27:26 weewx weewx[1468]: manager: Added record 2019-08-16 21:27:00 BST (1565987220) to daily summary in 'weewx.sdb'
Aug 16 21:27:26 weewx weewx[1468]: reportengine: Running reports for latest time in the database.
Aug 16 21:27:26 weewx weewx[1468]: vantage: Requesting 200 LOOP packets.
Aug 16 21:27:26 weewx weewx[1468]: reportengine: Running report 'SeasonsReport'
Aug 16 21:27:26 weewx weewx[1468]: reportengine: Found configuration file /etc/weewx/skins/Seasons/skin.conf for report 'SeasonsReport'
Aug 16 21:27:27 weewx weewx[1468]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras']
Aug 16 21:27:27 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:27:27 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:27:28 weewx weewx[1468]: cheetahgenerator: Generated 8 files for report SeasonsReport in 1.10 seconds
Aug 16 21:27:28 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:27:28 weewx weewx[1468]: imagegenerator: Generated 14 images for SeasonsReport in 0.45 seconds
Aug 16 21:27:28 weewx weewx[1468]: copygenerator: copied 5 files to /var/www/html/weewx
Aug 16 21:27:28 weewx weewx[1468]: reportengine: Report 'SmartphoneReport' not enabled. Skipping.
Aug 16 21:27:28 weewx weewx[1468]: reportengine: Report 'MobileReport' not enabled. Skipping.
Aug 16 21:27:28 weewx weewx[1468]: reportengine: Report 'StandardReport' not enabled. Skipping.
Aug 16 21:27:28 weewx weewx[1468]: reportengine: Report 'FTP' not enabled. Skipping.
Aug 16 21:27:28 weewx weewx[1468]: reportengine: Report 'RSYNC' not enabled. Skipping.
Aug 16 21:28:14 weewx weewx[1468]: vantage: Getting archive packets since 2019-08-16 21:27:00 BST (1565987220)
Aug 16 21:28:19 weewx weewx[1468]: vantage: Retry  #0 failed
Aug 16 21:28:24 weewx weewx[1468]: vantage: ip-read error: timed out
Aug 16 21:28:24 weewx weewx[1468]: vantage: Retry  #1 failed
Aug 16 21:28:24 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:28:26 weewx weewx[1468]: vantage: Retrieving 1 page(s); starting index= 0
Aug 16 21:28:26 weewx weewx[1468]: manager: Added record 2019-08-16 21:28:00 BST (1565987280) to database 'weewx.sdb'
Aug 16 21:28:26 weewx weewx[1468]: manager: Added record 2019-08-16 21:28:00 BST (1565987280) to daily summary in 'weewx.sdb'
Aug 16 21:28:26 weewx weewx[1468]: vantage: DMPAFT complete: page timestamp 2019-08-15 02:41:00 BST (1565833260) less than final timestamp 2019-08-16 21:28:00 BST (1565987280)
Aug 16 21:28:26 weewx weewx[1468]: vantage: Catch up complete.
Aug 16 21:28:26 weewx weewx[1468]: vantage: Requesting 200 LOOP packets.
Aug 16 21:28:26 weewx weewx[1468]: reportengine: Running reports for latest time in the database.
Aug 16 21:28:26 weewx weewx[1468]: reportengine: Running report 'SeasonsReport'
Aug 16 21:28:26 weewx weewx[1468]: reportengine: Found configuration file /etc/weewx/skins/Seasons/skin.conf for report 'SeasonsReport'
Aug 16 21:28:26 weewx weewx[1468]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras']
Aug 16 21:28:26 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:28:27 weewx weewx[1468]: cheetahgenerator: Generated 8 files for report SeasonsReport in 0.47 seconds
Aug 16 21:28:27 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:28:27 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:28:27 weewx weewx[1468]: imagegenerator: Generated 14 images for SeasonsReport in 0.44 seconds
Aug 16 21:28:27 weewx weewx[1468]: copygenerator: copied 0 files to /var/www/html/weewx
Aug 16 21:28:27 weewx weewx[1468]: reportengine: Report 'SmartphoneReport' not enabled. Skipping.
Aug 16 21:28:27 weewx weewx[1468]: reportengine: Report 'MobileReport' not enabled. Skipping.
Aug 16 21:28:27 weewx weewx[1468]: reportengine: Report 'StandardReport' not enabled. Skipping.
Aug 16 21:28:27 weewx weewx[1468]: reportengine: Report 'FTP' not enabled. Skipping.
Aug 16 21:28:27 weewx weewx[1468]: reportengine: Report 'RSYNC' not enabled. Skipping.
Aug 16 21:29:14 weewx weewx[1468]: vantage: Getting archive packets since 2019-08-16 21:28:00 BST (1565987280)
Aug 16 21:29:15 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:29:16 weewx weewx[1468]: vantage: Retrieving 1 page(s); starting index= 1
Aug 16 21:29:17 weewx weewx[1468]: manager: Added record 2019-08-16 21:29:00 BST (1565987340) to database 'weewx.sdb'
Aug 16 21:29:17 weewx weewx[1468]: manager: Added record 2019-08-16 21:29:00 BST (1565987340) to daily summary in 'weewx.sdb'
Aug 16 21:29:17 weewx weewx[1468]: vantage: DMPAFT complete: page timestamp 2019-08-15 02:42:00 BST (1565833320) less than final timestamp 2019-08-16 21:29:00 BST (1565987340)
Aug 16 21:29:17 weewx weewx[1468]: vantage: Catch up complete.
Aug 16 21:29:17 weewx weewx[1468]: vantage: Requesting 200 LOOP packets.
Aug 16 21:29:17 weewx weewx[1468]: reportengine: Running reports for latest time in the database.
Aug 16 21:29:17 weewx weewx[1468]: reportengine: Running report 'SeasonsReport'
Aug 16 21:29:17 weewx weewx[1468]: reportengine: Found configuration file /etc/weewx/skins/Seasons/skin.conf for report 'SeasonsReport'
Aug 16 21:29:17 weewx weewx[1468]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras']
Aug 16 21:29:17 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:29:17 weewx weewx[1468]: vantage: Gentle wake up of console successful
Aug 16 21:29:17 weewx weewx[1468]: cheetahgenerator: Generated 8 files for report SeasonsReport in 0.50 seconds
Aug 16 21:29:17 weewx weewx[1468]: manager: Daily summary version is 2.0
Aug 16 21:29:18 weewx weewx[1468]: imagegenerator: Generated 14 images for SeasonsReport in 0.43 seconds
Aug 16 21:29:18 weewx weewx[1468]: copygenerator: copied 0 files to /var/www/html/weewx
Aug 16 21:29:18 weewx weewx[1468]: reportengine: Report 'SmartphoneReport' not enabled. Skipping.
Aug 16 21:29:18 weewx weewx[1468]: reportengine: Report 'MobileReport' not enabled. Skipping.
Aug 16 21:29:18 weewx weewx[1468]: reportengine: Report 'StandardReport' not enabled. Skipping.
Aug 16 21:29:18 weewx weewx[1468]: reportengine: Report 'FTP' not enabled. Skipping.
Aug 16 21:29:18 weewx weewx[1468]: reportengine: Report 'RSYNC' not enabled. Skipping.

**Comment by gjr80** [comment] 2019-08-16 20:43
Jon,

Thanks, similar but slightly different error. In your case a None value for wind direction is causing the code to fail. I thought I had catered for that (having no wind direction when there is no wind is a common output from a weather station) but clearly not well enough. I will get on to this issue when I am back home in late August.

Gary

**Comment by u2kdd** [comment] 2020-02-29 11:34
Hi Gary

I think that I have the same Problem as Jon has. I use a Davis Vantage Pro 2 Station with weewx and it works round About 6 Hours and next morning I have found the below listed lines within the syslog.

**rtcrthread: Unexpected exception of type <type 'exceptions.TypeError'>
rtcrthread: Thread exiting. Reason: unsupported operand type(s) for -: 'float' and 'NoneType'**

Is it possible for you to solve the  @Problem?

BR
Ulf

**Comment by gjr80** [comment] 2020-02-29 11:43
I must confess to having forgotten about this one. #u2kdd could you provide a log extract like Jon provided showing the error you encountered.

Gary

**Comment by u2kdd** [comment] 2020-02-29 12:06
[syslog.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4270245/syslog.txt)
Hi Gary

Here it is ...
[syslog.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4270248/syslog.txt)

BR Ulf

**Comment by gjr80** [comment] 2020-02-29 12:19
Sorry to be a pain but could I get you to edit weewx.conf, set debug = 1, save weewx.conf and restart WeeWX. Then when the error occurs post a log extract showing the error trace.  At the moment I can tell there is a line of code that contains a difference between two variables and one of those variables is None (I suspect it will be wind related), problem is I don’t know which line of code it is. I am hoping that debug = 1 will show a more detailed error trace that will include the line number.

**Comment by u2kdd** [comment] 2020-02-29 12:33
I have modified weewx (debug=1). As soon as the error occurs you will get a log. At the Moment we have a bit wind but it will come …

BR Ulf

**Comment by u2kdd** [comment] 2020-02-29 13:12
[syslog.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4270322/syslog.txt)
Here is the new one ...

**Comment by gjr80** [comment] 2020-02-29 22:21
Thank, exactly what I need. Fixed at commit https://github.com/gjr80/weewx-realtime_clientraw/commit/8f26b8c4c257fa06eb9c43d93f0d3a0d77e1f87f.

Could you try running the latest `rtcr.py`, to do that:
1. rename your existing `rtcr.py` to `rtcr_orig.py` (it will be in `/home/weewx/bin/user` or `/usr/share/weewx/user` depending on your WeeWX install type)
2. download the updated `rtcr.py` from GitHub:
```
$ wget -P /var/tmp https://raw.githubusercontent.com/gjr80/weewx-realtime_clientraw/master/bin/user/rtcr.py
```
3. copy the downloaded `/var/tmp/rtcr.py` in place of the previous `rtcr.py` version
4. restart WeeWX

Check your log for any errors, the error just fixed was caused when there is no `windDir` (typically when `windSpeed == 0`) so it might be worthwhile keeping an eye on the log when `windSpeed` drops to zero and/or confirm that `clientraw.txt` is continuing to be updated after a period of no wind. If you do encounter any errors set `debug = 1` and restart WeeWX and when the error recurs post a copy of the error trace.

If needed you can revert to your existing install by deleting `rtcr.py`, renaming `rtcr_orig.py` back to `rtcr.py` and restarting WeeWX.

**Comment by u2kdd** [comment] 2020-03-01 11:13
Hi Gary
Many thanks for the fastest support ever which I've got over Internet. Currently it works and I hope it will remain. Sorry for my bad english.

Best regards from Dresden in Germany
Ulf

**Comment by gjr80** [comment] 2020-03-01 12:20
Ulf,
You are welcome, unfortunately this should have been fixed last year. And your English is fine, far better than my German!

Just to close this issue off, I have released v0.2.2 which fixes the error experienced by @u2kdd and @JonFear but I cannot be certain @Nebules had the same error.

I will close this issue, it can be re-opened or a new issue raised if there are further related problems.

**Closed by gjr80** 2020-03-01 12:20 UTC

**Comment by u2kdd** [comment] 2020-03-07 08:04
Hi Gary Here is once again Ulf from Dresden. I have found two files rtcr.py on my System. One is in /var/tmp and the other one in /usr/share/weewx/user.  If i put the below mentioned sentence in /etc/weewx/weewx.conf I can’t find a clientraw.txt but if I delete the sentence in weewx.conf I get a clientraw.txt in /var/tmp. Please try to help! BR Ulf   [RealtimeClientraw]    # Path to clientraw.txt. Relative paths are relative to HTML_ROOT. If    # empty default is HTML_ROOT. If setting omitted altogether default is    # /var/tmp    rtcr_path = /var/www/html/weewx/realtimeclientraw     # Minimum interval (seconds) between file generation. Ideally    # clientraw.txt would be generated on receipt of every loop packet (there    # is no point in generating more frequently than this); however, in some    # cases the user may wish to generate clientraw.txt less frequently. The    # min_interval option sets the minimum time between successive    # clientraw.txt generations. Generation will be skipped on arrival of a    # loop packet if min_interval seconds have NOT elapsed since the last    # generation. If min_interval is 0 or omitted generation will occur on    # every loop packet (as will be the case if min_interval < station loop    period). Optional, default is 0.    min_interval = 0     # Binding to use for appTemp data. Optional, default None.    additional_binding = None     # Update windrun value each loop period or just on each archive period.    # Optional, default is False.    windrun_loop = false     # Stations that provide partial packets are supported through a cache that    # caches packet data. max_cache_age is the maximum age  in seconds for    # which cached data is retained. Optional, default is 600 seconds.    max_cache_age = 600     avgspeed_period = 300    gust_period = 300     # Period in seconds over which to calculate trends. Anecdotally,    # clientraw.txt appears to use 1 hour for each but barometer trends are    # commonly calculated over a 3 hour period. Optional, default is 3600.    baro_trend_period = 3600    temp_trend_period = 3600    humidity_trend_period = 3600    humidex_trend_period = 3600     # Largest acceptable difference in seconds for whch a record is considered    # a match. Optional, default is 200.    grace = 200 Gesendet von Mail für Windows 10 Von: gjr80Gesendet: Sonntag, 1. März 2020 13:20An: gjr80/weewx-realtime_clientrawCc: u2kdd; MentionBetreff: Re: [gjr80/weewx-realtime_clientraw] rtcrthread: Unexpected exception of type <'exceptions.TypeError'> (#1) Closed #1.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gjr80/weewx-realtime_clientraw/issues/1?email_source=notifications\u0026email_token=AOVY23MWZAUWI7KHDSPGYODRFJHKXA5CNFSM4IHHUCM2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOW7UUNBY#event-3085518471",
"url": "https://github.com/gjr80/weewx-realtime_clientraw/issues/1?email_source=notifications\u0026email_token=AOVY23MWZAUWI7KHDSPGYODRFJHKXA5CNFSM4IHHUCM2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOW7UUNBY#event-3085518471",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gjr80** [comment] 2020-03-07 08:19
Ulf,
Could you open as a new issue please. Also the formatting appears all messed up and the content mixed with some other info. If submitting via the github web page you can preview your post before it is actually posted.
Gary

**Comment by u2kdd** [comment] 2020-06-06 13:41
Hi Gary
Can I ask you to have a look on a new issue? I have updated weewx and python and now I get the following error. Some others I have already solved.

[issue.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4740103/issue.txt)

BR from Dresden
