### ISSUE TITLE
realtimeclientraw contains a wrong value for max temperature

### ISSUE THREAD

**Issue by u2kdd** [gjr80/weewx-realtime_clientraw#6] opened 2021-01-30 10:52 UTC
Hello together

I have the problem that I get a wrong value for the maximum temperature of the day from weewex via clientraw. Attached you can see the result and also the clientraw .txt. I hope to get help!

BR Ulf from Dresden in GERMANY

[clientraw.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/5897781/clientraw.txt)

![Screenshot 2021-01-30 115045](https://user-images.githubusercontent.com/61574509/106354364-974d5480-62f1-11eb-8964-3c69d9424afe.png)

**Comment by gjr80** [comment] 2021-01-30 11:08
Hi,

That is a bit warm for you for this time of the year! Is your weather web site accessible from the internet, if so could you provide me with a link?

Gary

**Comment by u2kdd** [comment] 2021-02-06 10:04
Hi Gary
Do you have an idea which can help to solve the issue?
BR Ulf

**Comment by gjr80** [comment] 2021-02-11 03:34
Hi Ulf,

Did you see my response to your original post? I really don't have any idea what the issue could be, usually having a look at the other data on the site can give a clue to where to start looking, that was why I asked if your site was accessible via the internet. If not that is fine, I will then need to put together an instrumented version of the `rtcr.py` to log various things so we can see what is going on.

Gary

**Comment by u2kdd** [comment] 2021-02-11 04:34
Hi Gary
I think I told you, that you can see my site. Please have a look at u2kdd.de. Here you can find weewx and also "Tageswere" where you can see the dates of the day which are sometimes correct and sonstiges wrong.

Best regards
Ulf

11.02.2021 04:34:37 gjr80 <notifications@github.com>:

**Comment by gjr80** [comment] 2021-02-11 05:32
Thanks Ulf, don't remember but the address seems strangely familiar. In any case that is exactly what I was after. Let me see what I can come up with.
Gary

**Comment by gjr80** [comment] 2021-02-16 05:12
Ulf, I have watching both your WeeWX site and the 'Tageswerte' for a few days and have yet to see anything wrong on the 'Tageswerte'. It may be the time of day that I tend to be looking at your site, I am typically looking around 6-8am or 4-8pm my time  (I am +10 GMT so 8 hours ahead of you). I did happen to see the incorrect data once but not when I was able to investigate.

My first thoughts were that one field was being incorrectly formatted in `clientraw.txt` and that was cascading down causing problems elsewhere (as I guess you are aware `clientraw.txt` is a space delimited file so one missing space of data point throws out the parsing of the file). However, when I look at the `clientraw.txt` in your original post 39.5 is sitting right where it should in the daily maximum field and there appears to have been no shuffling of the data due to a malformed field.

39.5F is approx 4.2C which could be a plausible maximum for you for this time of year, but I am not seeing that type of incorrect conversion now; if such a conversion error was happening I would expect it to be there all the time.

I will continue to monitor.
Gary

**Comment by u2kdd** [comment] 2021-02-16 14:18
Hi Gary
Since yesterday I have not had the error but I have not changed anything. Normally I have seen it every evening 



16.02.2021 06:12:40 gjr80 <notifications@github.com>:

**Comment by gjr80** [comment] 2021-02-17 03:59
Ulf, I have just witnessed day max temp of 33.7C at 4:20am on 21 Feb your time. One thing I have noticed is that humidex, heatindex, windchill etc are all showing high values in the mid 30s C. I am still not sure what could be the cause but I am still thinking some temperatures are being interpreted using the wrong errors. I will put together an instrumented version of rtcr.py to log some loop and cache data. Can you confirm that you are using the latest rtcr release, ie v0.2.3?

Also, is your clientraw.txt publicly available on your web server, if so can you tell me where it is in respect to your web servers root. It would help to be able to see the file live.

Gary

**Comment by u2kdd** [comment] 2021-02-17 04:30
Hi Gary
Now you can also see the 33,7. The other questions I will answer in the evening our time.

17.02.2021 05:00:12 gjr80 <notifications@github.com>:

**Comment by hilman2** [comment] 2021-02-27 18:45
Hi gjr80,
i had the same problem. The script exports 046 - maximum day temperature (Celsius) not as °C but as °F.
I made a temporary fix by just calculating the right value while setting the [variable](url)

`# 046 - maximum day temperature (Celsius)
        if 'outTemp' in self.buffer:
            temp_th = self.buffer['outTemp'].day_max
        else:
            temp_th = None
        data[46] = (temp_th - 32) *5/9 if temp_th is not None else 0.0`

**Comment by u2kdd** [comment] 2021-02-27 19:14
Hi
Many thanks for answer concerning my problem. I am not an IT-expert but I hope it's a step in the right direction.

Best regards from Dresden in Germany!

27.02.2021 19:45:48 hilman2 <notifications@github.com>:

**Comment by gjr80** [comment] 2021-02-28 00:49
@hilman2 thanks for your input. I think you are correct in that there is an incorrect C/F conversion occurring, the problem is that for Ulf it is intermittent, sometimes it is correct and other times it is not.

@u2kdd I was waiting to hear which `rtcr.py` version you are running? Can you confirm it is version 0.2.3? I have been working on a new version that is WeeWX3/python2 and WeeWX4/python2/3 compatible. This version has a reworked buffer object that maintains the day max/min values, I am hopeful this will also cure the incorrect C/F conversion issue you are seeing. Can you also let me know where in your web servers directory tree I can find `clientraw.txt`, being able to see a live version of `clientraw.txt` is a big help in trying to track down issues such as this.

**Comment by gjr80** [comment] 2021-02-28 02:39
Actually Ulf, since you are using WeeWX v4.4.0 let's try the new WeeWX4 compatible version of `rtcr.py`. I tested it this morning under WeeWX4/python2/3 and it was well behaved. To install:

1. rename your existing `rtcr.py` in case we need to revert using:
```
$ sudo mv /usr/share/weewx/user/rtcr.py /usr/share/weewx/user/rtcr_orig.py 
```
if you installed WeeWX as a package otherwise use:
```
$ sudo mv /home/weewx/bin/user/rtcr.py /home/weewx/bin/user/rtcr_orig.py 
```
2. download the new `rtcr.py` in its place using:
```
$ sudo wget -P /usr/share/weewx/user/ https://raw.githubusercontent.com/gjr80/weewx-realtime_clientraw/python3/bin/user/rtcr.py
```
if you installed WeeWX as a package otherwise use:
```
$ sudo wget -P /home/weewx/bin/user/ https://raw.githubusercontent.com/gjr80/weewx-realtime_clientraw/python3/bin/user/rtcr.py
```
3. restart WeeWX

4. observe that `clientraw.txt` is bing generated and confirm there are no errors in the log.

If you run into errors then you can revert to the old `rtcr.py` by deleting the existing `rtcr.py` and renaming `rtcr_orig.py` back to `rtcr.py` using:
```
$ sudo mv /usr/share/weewx/user/rtcr_orig.py /usr/share/weewx/user/rtcr.py 
```
if you installed WeeWX as a package otherwise use:
```
$ sudo mv /home/weewx/bin/user/rtcr_orig.py /home/weewx/bin/user/rtcr.py 
```
If the incorrect day max temp issue remains let me know and I will send you an instrumented version of `rtcr.py` to log some info so we can work out what is going on/wrong.

**Comment by u2kdd** [comment] 2021-02-28 05:23
Hello all together

@Gary I think I told you 17 February that I use 0.3.0 dated 9 June 2020. But if you have not get the information I am sure that there was a mistake on my site. The link to the file was /home/www/u2kdd.de/wordpress/weewx/realtimeclientraw.

Now I will try the new version. I will inform both of you when I be sure if it works now or when the issue came again.

BR Ulf

**Comment by hilman2** [comment] 2021-02-28 07:08
Thanks for the new version. It's running without modification, live raw file is located here:

https://wetter.hilman.eu/data/weewx/clientraw.txt

**Comment by u2kdd** [comment] 2021-02-28 09:05
It`s the same here in Dresden.
BR Ulf

**Comment by u2kdd** [comment] 2021-02-28 09:05
I mean it works well at the moment.

**Comment by u2kdd** [comment] 2021-03-02 19:09
Hi Gary
Good news!!! I had no faults since the new rtcr.py was installed. Many thanks again for your support. Now I am more motivated to go further with my homepage.

BR from Dresden
Ulf

**Comment by hilman2** [comment] 2021-03-02 19:19
> Hi Gary
> Good news!!! I had no faults since the new rtcr.py was installed. Many thanks again for your support. Now I am more motivated to go further with my homepage.
> 
> BR from Dresden
> Ulf

Was hast du denn geplant? Meine WH2900 letzte Woche gekommen, bisher siehts so aus:
https://wetter.hilman.eu/ inkl. Dashboard fürs Smartphone und PWA um die Seite als "webapp" zu installieren.

WH2900 sendet per Ecowitt Protokoll an weewx das auf einem Raspyberry läuft. Per FTP landet die clientraw.txt auf meinem Webspace -> Wordpress mit WeatherStation, angereichert mit Daten von Openweathermap :)

**Comment by gjr80** [comment] 2021-03-03 07:19
> Hi Gary
> Good news!!! I had no faults since the new rtcr.py was installed. Many thanks again for your support. Now I am more motivated to go further with my homepage.
> 
> BR from Dresden
> Ulf

Good news Ulf, I am a little surprised as there were very few changes to the new file, certainly none that I was confident would fix the problem. No matter, I will leave this issue open for now and if I haven't heard back in a week or so I will close it. It can always be re-opened if need be.

**Comment by gjr80** [comment] 2021-03-13 07:36
Closing as issue appears fixed. Can be re-opened if required.

**Closed by gjr80** 2021-03-13 07:36 UTC
